### ISSUE TITLE
Thanks! and request

### ISSUE THREAD

**Issue by muchimi** [ashupp/Streamdeck-vJoy#1]
This is exactly what I was looking for - thanks for making this.

Couple of feature suggestions:
- ability to set a value on VJOY axis when pressing a button
- ability to do a keydown on a button, and keyup on a button as separate actions.  Combined with multi-action switch, this will allow for one deck button press to trigger and hold a button down on vjoy, and a second press to release that button.

Thanks!

**Comment by ashupp** [comment]
Hello and thank you.

May i ask for which game/app are you using this tool?
And does it actually work - also over some time?
Because I have not tested the plugin extensively :)

On your suggestions - these are actually great ideas. 
I will have a look at it.

Best regards

**Comment by ashupp** [comment]
@muchimi Check out the new release and tell me if this works for you. 
The axis behaviour seems a bit strange to me...
[https://github.com/ashupp/Streamdeck-vJoy/releases/tag/0.0.1.1](https://github.com/ashupp/Streamdeck-vJoy/releases/tag/0.0.1.1)


Best regards, Alex

**Comment by muchimi** [comment]
Will do, thanks for making the additions.   I use the deck for a number of flight simulations.  X-plane, Star Citizen among others.  I have several controllers joined via Joystick Gremlin, including some hardware panels.  The stream deck is a new addition so having the ability to output joystick buttons and axes is very helpful to help control some aspects of the sim.  Example, flaps, trim.   I also use supermacros for the keyboard side of things.  Having the ability to output VJOY items was the missing link.

**Comment by ashupp** [comment]
Ah i understand -  in the first place i created this plugin for simracing. but in the meantime i have mapped all my needs to keyboard shortcuts. So i am using it no longer right now. I didnt know Joystick Gremlin - very interesting. Sounds like you have a serious flight rig there :)

**Comment by muchimi** [comment]
I tried version 1.1.  Perfect -  button press/release and the axis min/max/center.

One of the needs in flight sim is to "nudge" or set a specific value on the axis.  Example: 5% of total travel if your mapping is a power output, vs 25% or whatever is needed.  So not always min/max/center.  Gremlin uses -1 to +1 with 0 as the center, and the values expressed as floating point, so -0.9 would be 5%.  Any way to accept a number value for an axis output and use that as the output?

**Comment by ashupp** [comment]
Thank you for the feedback. I will have a look at it. An easy way would be to just put a desired number for axis value when pressed. Possible value for each axis is 0-65535. Would this already fit your needs?

**Comment by muchimi** [comment]
Yep that works.  This way a press can set a value temporarily, and then reset the value to another when released.  Excellent to "pulse" something like a thruster or a control surface like a trim.  

I was also thinking icing on the cake would be to "add" a value to the current axis.  A positive number or a negative number.   Good example of this would be a flap.   Press one button to add 10%, press another to remove 10%.  No effect below 0 or higher than 0xFFFF (65535).

**Comment by ashupp** [comment]
Check out the new release:
https://github.com/ashupp/Streamdeck-vJoy/releases/tag/0.0.1.3
When using step up or step down you should first check "do nothing" on button release so the step is not reset when releasing the button.

But of course you could step up 1000 on press and step down 500 on release.
I dont know if this makes any sense :)

You can also perform a press and hold until its released combined with stepper this way.

Many possibilitys - send me the pluginlog.log inside the plugin directory if something does not work as intended. Also try if deleting and re-creating the button new solves a temporary problem. (Restart of Streamdeck does also somtimes)

**Comment by benkayuk** [comment]
Just to say...I've been looking for a way for StreamDeck to issue game controller presses since day 1. SimDeck I didn't like so much, but your plugin works perfectly...I couldn't be happier and it makes the StreamDeck the perfect button box!

**Comment by muchimi** [comment]
Alexander - your new release worked just fine.
I was in fact able to use the Streamdeck to send output to a VJOY device, and use that as an input inside Joystick Gremlin which is terrific.  I'll let the Gremlin crew know because this is the first time I think I've seen that work.  Cheers!

**Comment by ashupp** [comment]
Thank you for the information. Great to see the plugin is working for you and hopefully a lot more people.

During fixing the sticky buttons issue in 0.0.1.4 i have noticed another behaviour:

The first time you click a button the value of a vjoy device all available axis of the device will be set to 0. Did you notice this behaviour? Actually this is a problem for me in at least one Game. (Project Cars 2). Or is this smoothed because you are using Joystick Gremlin?

Thank you and best regards, Alex

**Comment by muchimi** [comment]
Yes it does set it to zero the first time.  You have to give it a default value - usually 50%.  When a profile is started in Gremlin, this is set for you.  Perhaps setting a default value when the plugin / profile is loaded?

**Comment by muchimi** [comment]
Alex -
I have one more question for you.
The "step up" and "step down" function works well, but when I have a third
button to re-center, the step up/step down values don't get reset (it
doesn't re-read the axis).
What I was thinking is that if you recenter the axis, the step up/down
functions should be not from the last step up or down, but from the current
axis position.
This is also true if I modify the axis in question from some other function.

What I'm experiencing right now is that the step functions are
working together, but ignore any centering.

Does that make sense?

Regards,

EM

**Comment by muchimi** [comment]
Sorry Alex! Me again.

I decided to fork the project so I could play with the code without messing
your stuff up.  I added a few changes to fix the issue I was having that I
think are doing the trick

https://github.com/muchimi/Streamdeck-vJoy

A next step would be to have sticky keys - meaning - step up and step down
constantly applied on tick() as long as the button is pressed.

**Comment by ashupp** [comment]
Hello,

thank you for the request. I think i asked this question on nov. 22. if it would be better if the axis could be manipulated by another button as well :) Great you solved it already.

You are welcome to extend the functionality 👍 Great!.

It could take some weeks for me to check the things again and push the project further as i am currently involved in another project.

Best regards, Alex

**Comment by SierraDelta7** [comment]
Hi Alex, 

I hope this message finds you well.
First, I would like to thank you for your excellent work. I love this plugin. 

Like Muchimi, I am using vJoy with X-Plane 11 to control various simulation functions. I have one small issue however. With your plugin (ver 0.0.1.4) I am not able to add vJoy actions to StreamDeck multi-action buttons or switches. Have I done something incorrectly?

Lastly, I would like to add myself to the list of people that would use a "latching" button function. I would contribute myself if I had the skills. 

Best regards.

**Comment by ashupp** [comment]
@SierraDelta7 
Hello and thank you. 
I have enabled the Plugin for Multi-Actions. Please give it a try and tell me if this works for you.
https://github.com/ashupp/Streamdeck-vJoy/releases/tag/0.0.1.5

Could you describe detailed what kind of functionality you mean with "latching"?

Best regards, Alex

**Comment by SierraDelta7** [comment]
Hi Alex,
That was fast! The 0.0.1.5 release seems to work perfectly.

The latching function would allow the first press of a button to hold the vJoy button down. A second press of the **same** button would release the vJoy button. 

Adding the multi-action functionality is a work-around because you already have the push & hold / release functions built in. I can make steps for the push/hold and release. Before you enabled the multi-action function I would have used two separate buttons on my streamdeck. One for the push/hold the vJoy button and the second to release that vJoy button. 

Thanks again for your work on this project, its fantastic!

**Comment by muchimi** [comment]
For what it's worth - I do this via joystick gremlin because latching and
other advanced control behavior was a bit beyond "get the streamdeck to
output a button".
Anything along the lines of long press vs short press and toggle - I find
it much easier to do inside gremlin as it has built-in features for this.
My mapping is   streamdeck -> vjoy 4 -> gremlin -> vjoy 1 to 3 ->
simulation titles.
Gremlin also handles my other input devices (yoke, pedals, throttle,
sticks) so I can easily change configurations per aircraft, or per
simulator I use.

This is another option that doesn't require changes to the plugin.

Cheers,

M

**Comment by ashupp** [comment]
Thanks for your help muchimi. joystick gremlin seems to be such a useful tool since it can handle so many stuff the plugin currently doesent :) 

I added an additional action for simple latching button / toggle.
This is currently only for button - no axis or specific values yet.

New release here:
https://github.com/ashupp/Streamdeck-vJoy/releases/tag/0.0.1.6
Please read warning before install.

happy easter and best regards, Alex
