### ISSUE TITLE
Multiple Buttons in a single Action.

### ISSUE THREAD

**Issue by WillFM** [ashupp/Streamdeck-vJoy#3]
It would be nice to be able to combine multiple simultaneous button presses to a single action.

As in, right now, you type in a vJoy Button #, in the box, it would be nice if you could put a delimited list of buttons, and have them all trigger by the action. 

e.g. i'd like to be able to enter "1,4"  or "2,4,5" etc.

**Comment by WillFM** [comment]
[relevant PR](https://github.com/ashupp/Streamdeck-vJoy/pull/4)

**Comment by Tonysw83** [comment]
yes would definitely would be a nice thing to have multiple  button presses from one button press but there is no need really as we already have multiple actions option stream deck software

**Comment by ashupp** [comment]
Hello and thanks for the comments and pull request. 
Sorry for the delayed answer.
As @Tonysw83 already said this fuctionality is already given by multi action composing with even more flexibility.
I will think about adding it in a future release.
