### ISSUE TITLE
Doesn't seem to work with vJoy 2.2.1.1

### ISSUE THREAD

**Issue by IslandJohn** [ashupp/Streamdeck-vJoy#7]
I upgraded from 2.1.9.1 to 2.2.1.1 from https://github.com/njz3/vJoy and the plugin stopped working. Feeder/monitor work as expected, but once feeder is stopped there's no input through this plugin and Stream Deck. Any thoughts on what may have changed?

**Comment by ashupp** [comment]
Hello, thanks for the message. This plugin was only tested with 2.1.9.1.
However i will see whats the matter with the newer version soon. Could be only a linking issue since its fact the API of the older version is referenced by this Application.

**Comment by taylorthurlow** [comment]
Any chance of taking a look at this?

**Comment by ashupp** [comment]
Hello and thanks for your message @IslandJohn, @taylorthurlow .

I have created a new release for 2.2.1.1.
Please provide feedback since it was not really tested yet.

Download here:
https://github.com/ashupp/Streamdeck-vJoy/releases/tag/0.0.2.0

Best regards, Alex

**Comment by taylorthurlow** [comment]
@ashupp Sorry for the delay, just wanted to say that I've been using this for a few days and I haven't had any issues. Thanks for updating!
