### ISSUE TITLE
How to install this plugin?

### ISSUE THREAD

**Issue by henryhkf** [ashupp/Streamdeck-vJoy#9]
I have downloaded this plugin and save it into the Plugin Folder on Stream Deck root.

but can't see listed on the Stream deck application.

**Comment by ashupp** [comment]
You have to download the plugin file from the releases tab and install it by double clicking on it.
The file is called "com.streamdeck.vjoy.streamDeckPlugin" you can find it on the assets list of the latest release.
Also make sure you are using the correct version of vJoy. The current version of this plugin works with vjoy v2.1.9.1.
[https://github.com/ashupp/Streamdeck-vJoy/releases](https://github.com/ashupp/Streamdeck-vJoy/releases)

**Comment by beecreate** [comment]
> 
> 
> You have to download the plugin file from the releases tab and install it by double clicking on it.

FYI... the releases tab doesnt show; hard link to the tab works
![image](https://user-images.githubusercontent.com/62603552/101991029-4edac880-3caa-11eb-815f-b1833982f4b5.png)

**Comment by ashupp** [comment]
Thank you. 
It seems github redesigned a bit and removed the releases tab. The releases link moved to the right.
I have updated the note on the main page.
![image](https://user-images.githubusercontent.com/1867828/102004031-030d3b00-3d0d-11eb-9981-471be96a5059.png)
